# Changes here will be overwritten by Copier
_commit: v0.3.2
_src_path: gh://lsstdesc/RAIL-project-template
author_email: lsst-desc-rail-admin@slac.stanford.edu
author_name: LSST Dark Energy Science Collaboration (DESC)
create_example_module: false
package_name: deepdisc
project_name: pz-rail-deepdisc
