# This workflow will install Python dependencies, run tests and report code coverage with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Mamba - Unit test and code coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3

    - uses: mamba-org/setup-micromamba@v1
      with:
        create_args: >-
          python=${{ matrix.python-version }}
        channels: conda-forge,defaults
        channel-priority: strict
        show-channel-urls: true
        environment-file: ci-environment.yml
        activate-environment: deepdisc

    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        pip install .
        pip install .[dev]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run unit tests with pytest
      run: |
        python -m pytest tests --cov=deepdisc --cov-report=xml
    - name: Upload coverage report to codecov
      uses: codecov/codecov-action@v3
